services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ..
      dockerfile: deploy/web/Dockerfile
    container_name: flask_app
    restart: always
    env_file:
      - ../.env
    expose:
      - "5000"
    depends_on:
      - db
    volumes:
      - ..:/app

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      # "443:443" quand tu rajouteras SSL
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../static:/app/static
    depends_on:
      - web

volumes:
  postgres_data:


#  certbot:
#    image: certbot/certbot
#    container_name: certbot
#    restart: always
#    volumes:
#      - ./certbot/conf:/etc/letsencrypt
#      - ./certbot/www:/var/www/certbot
