"""add user_resquests talbe

Revision ID: 028b67c021ac
Revises: 674c75138957
Create Date: 2025-09-16 14:21:20.024908

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "028b67c021ac"
down_revision = "674c75138957"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("admin", schema=None) as batch_op:
        batch_op.alter_column(
            "username",
            existing_type=sa.VARCHAR(length=150),
            type_=sa.String(length=64),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.VARCHAR(length=512),
            type_=sa.String(length=84),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "email",
            existing_type=sa.VARCHAR(length=150),
            type_=sa.String(length=120),
            existing_nullable=False,
            existing_server_default=sa.text("'default@example.com'::character varying"),
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "username",
            existing_type=sa.VARCHAR(length=150),
            type_=sa.String(length=64),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "email",
            existing_type=sa.VARCHAR(length=150),
            type_=sa.String(length=120),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "email",
            existing_type=sa.String(length=120),
            type_=sa.VARCHAR(length=150),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "username",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=150),
            existing_nullable=False,
        )

    with op.batch_alter_table("admin", schema=None) as batch_op:
        batch_op.alter_column(
            "email",
            existing_type=sa.String(length=120),
            type_=sa.VARCHAR(length=150),
            existing_nullable=False,
            existing_server_default=sa.text("'default@example.com'::character varying"),
        )
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.String(length=84),
            type_=sa.VARCHAR(length=512),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "username",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=150),
            existing_nullable=False,
        )

    op.drop_table("user_requests")
    # ### end Alembic commands ###
