"""initial schema

Revision ID: 0bb412158f0d
Revises:
Create Date: 2025-09-10 20:09:51.383336

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0bb412158f0d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=True),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=150), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("firstname", sa.String(length=150), nullable=False),
        sa.Column("lastname", sa.String(length=150), nullable=False),
        sa.Column("email", sa.String(length=150), nullable=False),
        sa.Column("fidelity_level", sa.Integer(), nullable=True),
        sa.Column("fidelity_cycle", sa.Integer(), nullable=True),
        sa.Column("consent_privacy", sa.Boolean(), nullable=False),
        sa.Column("consent_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_approved", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("is_anonymized", sa.Boolean(), nullable=True),
        sa.Column("admin_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["admin_id"],
            ["admin.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("username_at_time", sa.String(length=250), nullable=False),
        sa.Column("is_visible", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fidelity_reward_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("level_reached", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cycle_number", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fidelity_reward_log")
    op.drop_table("comment")
    op.drop_table("user")
    op.drop_table("admin")
    # ### end Alembic commands ###
