"""add 'is_visible' in the 'Comment' table

Revision ID: 0cae6d08e555
Revises: 711a4d13bbb8
Create Date: 2025-06-18 09:26:46.561917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cae6d08e555'
down_revision = '711a4d13bbb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###
