"""user_id nullable=True

Revision ID: 217f99e4d7de
Revises: a6a2037e93cb
Create Date: 2025-06-16 10:13:51.177135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217f99e4d7de'
down_revision = 'a6a2037e93cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
