"""Add fidelity_cycle to User and cycle_number to FidelityRewardLog

Revision ID: 2feac6f0836f
Revises: d1e206accc18
Create Date: 2025-05-16 10:35:01.723585

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2feac6f0836f"
down_revision = "d1e206accc18"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fidelity_reward_log", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("cycle_number", sa.Integer(), nullable=False, server_default="0")
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("fidelity_cycle", sa.Integer(), nullable=True, server_default="0")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("fidelity_cycle")

    with op.batch_alter_table("fidelity_reward_log", schema=None) as batch_op:
        batch_op.drop_column("cycle_number")

    # ### end Alembic commands ###
