"""add email field to User and Admin

Revision ID: 3a80e4aa0e0e
Revises: 5f26d8766823
Create Date: 2025-05-15 16:39:10.207406

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3a80e4aa0e0e"
down_revision = "5f26d8766823"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admin", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "email", sa.String(length=150), nullable=False, server_default=None
            )
        )
        batch_op.create_unique_constraint(None, ["email"])

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "email", sa.String(length=150), nullable=False, server_default=None
            )
        )
        batch_op.create_unique_constraint(None, ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("email", server_default="default@example.com")

    with op.batch_alter_table("admin", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("email", server_default="default@example.com")

    # ### end Alembic commands ###
