"""Make user_id nullable in fidelity_reward_log

Revision ID: 455be26969d8
Revises: 47d25fb0a618
Create Date: 2025-06-10 13:49:04.161523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455be26969d8'
down_revision = '47d25fb0a618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fidelity_reward_log', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fidelity_reward_log', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
