"""Add two colums in User

Revision ID: 47d25fb0a618
Revises: df036c24486f
Create Date: 2025-06-10 11:56:58.615522

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "47d25fb0a618"
down_revision = "df036c24486f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("consent_privacy", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("consent_date", sa.DateTime(), nullable=True))

    op.execute(
        'UPDATE "user" SET consent_privacy = false WHERE consent_privacy IS NULL'
    )
    # ### end Alembic commands ###

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column("consent_privacy", nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("consent_date")
        batch_op.drop_column("consent_privacy")

    # ### end Alembic commands ###
