"""partial unique on user email/username

Revision ID: 4c374db4615a
Revises: 028b67c021ac
Create Date: 2025-09-16 15:47:29.185433

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4c374db4615a"
down_revision = "028b67c021ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("user_email_key", type_="unique")
        batch_op.drop_constraint("user_username_key", type_="unique")

    # Créer les index uniques partiels
    op.create_index(
        "uq_user_email_active",
        "user",
        ["email"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_user_username_active",
        "user",
        ["username"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    # ### end Alembic commands ###


def downgrade():
    # Supprimer les index partiels
    op.drop_index("uq_user_username_active", table_name="user")
    op.drop_index("uq_user_email_active", table_name="user")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_unique_constraint("user_username_key", ["username"])
        batch_op.create_unique_constraint("user_email_key", ["email"])

    # ### end Alembic commands ###
