"""sync models

Revision ID: 674c75138957
Revises: 0bb412158f0d
Create Date: 2025-09-16 11:53:38.211696

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "674c75138957"
down_revision = "0bb412158f0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fidelity_reward_log", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fidelity_level", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("fidelity_cycle", sa.Integer(), nullable=True))

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.VARCHAR(length=512),
            type_=sa.String(length=84),
            existing_nullable=False,
        )
        batch_op.drop_column("fidelity_cycle")
        batch_op.drop_column("fidelity_level")
        batch_op.drop_column("lastname")
        batch_op.drop_column("firstname")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "firstname", sa.VARCHAR(length=150), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "lastname", sa.VARCHAR(length=150), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "fidelity_level", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "fidelity_cycle",
                sa.INTEGER(),
                server_default=sa.text("0"),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.alter_column(
            "password_hash",
            existing_type=sa.String(length=84),
            type_=sa.VARCHAR(length=512),
            existing_nullable=False,
        )

    with op.batch_alter_table("fidelity_reward_log", schema=None) as batch_op:
        batch_op.drop_column("fidelity_cycle")
        batch_op.drop_column("fidelity_level")

    # ### end Alembic commands ###
