"""Add deleted_at column to User for soft delete

Revision ID: 711a4d13bbb8
Revises: 217f99e4d7de
Create Date: 2025-06-17 10:15:23.073150

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "711a4d13bbb8"
down_revision = "217f99e4d7de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("deleted_at")

    # ### end Alembic commands ###
