"""add password_hash at UserRequest class

Revision ID: 738adf70f44a
Revises: 7d12ab2ffccb
Create Date: 2025-09-16 17:49:18.671188

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "738adf70f44a"
down_revision = "7d12ab2ffccb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_hash", sa.String(length=84), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_requests", schema=None) as batch_op:
        batch_op.drop_column("password_hash")

    # ### end Alembic commands ###
