"""Remplacement de password en password_hash dans la classe 'User'

Revision ID: 74c1ec1c036a
Revises: c80feb63e104
Create Date: 2025-05-09 17:34:15.264327

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "74c1ec1c036a"
down_revision = "c80feb63e104"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_hash", sa.String(length=150), nullable=False)
        )
        batch_op.drop_column("password")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "password", sa.VARCHAR(length=150), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column("password_hash")

    # ### end Alembic commands ###
