"""Ajout de la classe Comment

Revision ID: 95f5848b40ea
Revises: 0dba4015ec88
Create Date: 2025-05-13 17:26:09.444556

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "95f5848b40ea"
down_revision = "0dba4015ec88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment")
    # ### end Alembic commands ###
