"""add is_anonymized in 'User' table

Revision ID: 99e553435d0d
Revises: 0cae6d08e555
Create Date: 2025-06-18 10:05:41.244147

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "99e553435d0d"
down_revision = "0cae6d08e555"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_anonymized", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("is_anonymized")

    # ### end Alembic commands ###
