"""add username_at_time

Revision ID: a6a2037e93cb
Revises: 9fb14e32edca
Create Date: 2025-06-16 10:12:20.285665

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a6a2037e93cb"
down_revision = "9fb14e32edca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("username_at_time", sa.String(length=250), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_column("username_at_time")

    # ### end Alembic commands ###
