"""Add admin in user

Revision ID: df036c24486f
Revises: 2feac6f0836f
Create Date: 2025-05-16 12:17:59.826924

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "df036c24486f"
down_revision = "2feac6f0836f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("admin_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "admin", ["admin_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("admin_id")

    # ### end Alembic commands ###
